---
- name: Configure Sogo
  hosts: localhost

  tasks:
    - name: Template a file to /etc/sogo/sogo.conf.j2
      ansible.builtin.template:
        src: /etc/sogo/sogo.conf.j2
        dest: /etc/sogo/sogo.conf

    - name: Template a file to /etc/nginx/nginx.conf.j2
      ansible.builtin.template:
        src: /etc/nginx/nginx.conf.j2
        dest: /etc/nginx/nginx.conf