#!/usr/bin/with-contenv sh
echo "Starting nginx...."
nginx
echo "Waiting Mysql instance....."
while ! mysqladmin status -h ${SOGO_MYSQL_HOST} -usogo -psogo --silent; do
  echo "Waiting for database to come up..."
  sleep 2
done
echo "Create your account...."
/usr/bin/mysql -h ${SOGO_MYSQL_HOST} -usogo -psogo --database sogo < /tmp/auth_sogo.sql
echo "Starting sogod...."
su -s /bin/bash -c '/usr/sbin/sogod -WOWorkersCount 15 -WOPidFile /var/run/sogo/sogo.pid -WOPort 0.0.0.0:20000 -WOLogFile -' sogo